name: OWASP ZAP integration with github actions

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://transactions.sendowl.com/orders/165514814/download/50b58a5b03969191c246f372f5f8fb88'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'